apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web
  name: listee-web
  labels:
    app: listee
    svc: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listee
      svc: web
  template:
    metadata:
      labels:
        app: listee
        svc: web
    spec:
      containers:
      - name: listee-web
        image: registry.git.rwth-aachen.de/aix-pizza-time/listee-web:2.0.2
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
      imagePullSecrets:
      - name: gitlab
      restartPolicy: Always